import AnimateInView from '@/components/AnimateInView';

export default function ProductShowcase() {
  return (
    <div className='space-y-20 sm:space-y-28'>
      {/* Section 1: Idea Details — Mock left, text right */}
      <div className='flex flex-col lg:flex-row items-center gap-10 lg:gap-16'>
        <AnimateInView className='w-full lg:w-[50%] shrink-0' y={30}>
          <div className='rounded-xl border border-white/10 bg-white/[0.02] shadow-2xl shadow-primary-500/5 overflow-hidden pointer-events-none select-none max-h-[520px]'>
            <div className='p-4 scale-[0.75] origin-top-left w-[133.33%]'>
              <IdeaDetailMock />
            </div>
          </div>
        </AnimateInView>

        <AnimateInView className='w-full lg:w-[45%]' y={30} delay={0.1}>
          <p className='text-xs font-semibold uppercase tracking-widest text-primary-500 mb-3'>Idea Details</p>
          <h2
            className='text-white text-3xl sm:text-4xl font-bold mb-4'
            style={{ fontFamily: 'var(--font-zalando-sans-expanded)' }}
          >
            Your Idea, Structured
          </h2>
          <p className='text-white/50 text-sm sm:text-base leading-relaxed'>
            Present your startup idea with clarity. Define the problem, your solution, and who it&apos;s for — then let the
            community and AI do the rest. Every idea gets the structure it needs to be properly validated.
          </p>
        </AnimateInView>
      </div>

      {/* Section 2: Market Insights — Text left, mock right */}
      <div className='flex flex-col-reverse lg:flex-row items-center gap-10 lg:gap-16'>
        <AnimateInView className='w-full lg:w-[45%]' y={30} delay={0.1}>
          <p className='text-xs font-semibold uppercase tracking-widest text-accent-500 mb-3'>Market Insights</p>
          <h2
            className='text-white text-3xl sm:text-4xl font-bold mb-4'
            style={{ fontFamily: 'var(--font-zalando-sans-expanded)' }}
          >
            AI-Powered Market Intelligence
          </h2>
          <p className='text-white/50 text-sm sm:text-base leading-relaxed'>
            Instantly understand your market landscape. Get TAM estimates, growth projections, competitor breakdowns, and
            a realistic difficulty assessment — all generated by AI the moment you post your idea.
          </p>
        </AnimateInView>

        <AnimateInView className='w-full lg:w-[50%] shrink-0' y={30}>
          <div className='rounded-xl border border-white/10 bg-white/[0.02] shadow-2xl shadow-accent-500/5 overflow-hidden pointer-events-none select-none max-h-[520px]'>
            <div className='p-4 scale-[0.75] origin-top-left w-[133.33%]'>
              <MarketInsightsMock />
            </div>
          </div>
        </AnimateInView>
      </div>
    </div>
  );
}

/* ─── Idea Detail Mock ─── */
function IdeaDetailMock() {
  return (
    <div className='bg-surface-variant rounded-lg p-5 sm:p-6'>
      {/* Author & Date */}
      <div className='flex items-center justify-between mb-5'>
        <div className='flex items-center gap-3'>
          <div className='w-9 h-9 rounded-full bg-primary-500/20 flex items-center justify-center'>
            <span className='text-xs font-semibold text-primary-400'>A</span>
          </div>
          <div>
            <p className='text-sm font-medium text-white'>Alex Chen</p>
            <p className='text-xs text-white/50'>@alexchen</p>
          </div>
        </div>
        <span className='text-xs text-white/40'>Posted on Jan 15, 2025</span>
      </div>

      {/* Badges */}
      <div className='flex flex-wrap items-center gap-2 mb-3'>
        <span className='px-2 py-0.5 rounded text-xs font-medium bg-primary-500/15 text-primary-400'>SaaS</span>
        <span className='px-2 py-0.5 rounded text-xs font-medium bg-accent-500/15 text-accent-400'>Concept</span>
        <span className='px-2 py-0.5 rounded text-xs font-medium bg-green-500/15 text-green-400'>
          Looking for Co-founder
        </span>
      </div>

      {/* Tags */}
      <div className='flex flex-wrap gap-1.5 mb-5'>
        {['AI', 'Productivity', 'B2B'].map((tag) => (
          <span key={tag} className='px-2 py-0.5 rounded text-xs bg-white/5 text-white/50'>
            {tag}
          </span>
        ))}
      </div>

      {/* Title */}
      <h3 className='text-lg sm:text-xl font-bold text-white mb-5'>
        An AI assistant that automates weekly team status reports
      </h3>

      {/* Content Sections */}
      <div className='space-y-3'>
        <div className='p-3 bg-surface rounded-lg'>
          <p className='text-xs font-medium text-accent-500 mb-1.5'>Problem</p>
          <p className='text-sm text-white/70 leading-relaxed'>
            Engineering managers spend 3-5 hours weekly compiling status reports from multiple tools. Information is
            scattered across Slack, Jira, and GitHub, making it tedious to track progress.
          </p>
        </div>
        <div className='p-3 bg-surface rounded-lg'>
          <p className='text-xs font-medium text-accent-500 mb-1.5'>Solution</p>
          <p className='text-sm text-white/70 leading-relaxed'>
            An AI agent that connects to your project tools and auto-generates comprehensive weekly reports with key
            metrics, blockers, and team highlights.
          </p>
        </div>
        <div className='p-3 bg-surface rounded-lg'>
          <p className='text-xs font-medium text-accent-500 mb-1.5'>Target Audience</p>
          <p className='text-sm text-white/70 leading-relaxed'>
            Engineering managers and team leads at mid-size tech companies with 50+ engineers.
          </p>
        </div>
      </div>

      {/* Vote Buttons */}
      <div className='mt-5 pt-5 border-t border-white/10'>
        <div className='flex flex-wrap items-center gap-2'>
          <div className='flex items-center gap-2 px-3 h-8 rounded-lg bg-accent-500/20 text-accent-500'>
            <svg className='w-4 h-4' fill='currentColor' viewBox='0 0 24 24'>
              <path d='M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3H14zM4 22H2V11h2v11z' />
            </svg>
            <span className='text-sm font-medium'>24</span>
            <span className='text-sm font-medium'>Useful</span>
          </div>
          <div className='flex items-center gap-2 px-3 h-8 rounded-lg bg-white/5 text-white/60'>
            <svg className='w-4 h-4' fill='currentColor' viewBox='0 0 24 24'>
              <path d='M10 15v4a3 3 0 0 0 3 3l4-9V2H5.72a2 2 0 0 0-2 1.7l-1.38 9a2 2 0 0 0 2 2.3H10zM20 2h2v11h-2V2z' />
            </svg>
            <span className='text-sm font-medium'>3</span>
            <span className='text-sm font-medium'>Not Useful</span>
          </div>
        </div>
      </div>
    </div>
  );
}

/* ─── Market Insights Mock ─── */
function MarketInsightsMock() {
  return (
    <div className='space-y-3'>
      <h3 className='text-base font-semibold text-white'>Market Insights</h3>

      {/* TAM / CAGR Grid */}
      <div className='grid grid-cols-2 gap-3'>
        <div className='p-4 bg-surface-variant rounded-lg'>
          <p className='text-xs font-medium text-accent-500 mb-1'>TAM</p>
          <p className='text-lg font-semibold text-white'>$4.2B</p>
        </div>
        <div className='p-4 bg-surface-variant rounded-lg'>
          <p className='text-xs font-medium text-accent-500 mb-1'>CAGR</p>
          <p className='text-lg font-semibold text-white'>22.1%</p>
        </div>
        <div className='p-4 bg-surface-variant rounded-lg col-span-2'>
          <p className='text-xs font-medium text-accent-500 mb-1'>Market Size</p>
          <p className='text-sm text-white/70'>
            The project management and team reporting tools market is valued at $4.2B in 2025.
          </p>
        </div>
        <div className='p-4 bg-surface-variant rounded-lg col-span-2'>
          <p className='text-xs font-medium text-accent-500 mb-1'>Market Growth</p>
          <p className='text-sm text-white/70'>
            Expected to reach $11.4B by 2030, driven by remote work and AI adoption.
          </p>
        </div>
      </div>

      {/* Competitors */}
      <div className='p-4 bg-surface-variant rounded-lg'>
        <p className='text-xs font-medium text-accent-500 mb-3'>Competitors</p>
        <div className='space-y-2'>
          {[
            { name: 'Slack', share: '15%', revenue: '$1.5B' },
            { name: 'Jira', share: '22%', revenue: '$2.1B' },
            { name: 'Linear', share: '4%', revenue: '$150M' },
          ].map((c) => (
            <div key={c.name} className='flex items-center justify-between py-2 border-b border-white/5 last:border-0'>
              <span className='text-sm font-medium text-white'>{c.name}</span>
              <div className='flex items-center gap-4 text-xs text-white/60'>
                <span>{c.share} share</span>
                <span>{c.revenue}</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Share / Opportunity */}
      <div className='grid grid-cols-2 gap-3'>
        <div className='p-4 bg-surface-variant rounded-lg'>
          <p className='text-xs font-medium text-accent-500 mb-1'>Your Estimated Share</p>
          <p className='text-lg font-semibold text-white'>2-4%</p>
        </div>
        <div className='p-4 bg-surface-variant rounded-lg'>
          <p className='text-xs font-medium text-accent-500 mb-1'>Market Opportunity</p>
          <p className='text-sm text-white/70'>Strong demand for AI-native reporting — most tools still require manual input.</p>
        </div>
      </div>

      {/* Difficulty */}
      <div className='p-4 bg-surface-variant rounded-lg'>
        <p className='text-xs font-medium text-accent-500 mb-1'>Implementation Difficulty</p>
        <p className='text-sm text-white/70 leading-relaxed'>
          Moderate — requires deep integrations with existing tools but leverages well-established APIs.
        </p>
      </div>
    </div>
  );
}
